server:
  port: 8081
spring:
  application:
      name: market-service
  datasource:
    url: jdbc:postgresql://market-db:5432/marketdb
    username: market
    password: market
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/trading-platform
          jwk-set-uri: http://keycloak:8080/realms/trading-platform/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: redis
      port: 6379

market-data:
  enabled: true
  endpoint-url: ${MARKET_DATA_ENDPOINT_URL:http://market-data:8085/api/market-data}
  refresh-interval-ms: ${MARKET_DATA_REFRESH_INTERVAL_MS:60000}
  default-market: ${MARKET_DATA_DEFAULT_MARKET:TUNIS}
  default-currency: ${MARKET_DATA_DEFAULT_CURRENCY:TND}