server:
  port: 8081
spring:
  application:
    name: market-service
  datasource:
    url: jdbc:postgresql://localhost:5432/marketdb
    username: market
    password: market
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/trading-platform