services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports: ["8080:8080"]
    depends_on: [keycloak-db]
    volumes:
      -  ./auth:/opt/keycloak/data/import

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes: [keycloak_data:/var/lib/postgresql/data]

  market-db:
    image: postgres:16
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    ports:
        - "5433:5432"
    volumes: [ market_data:/var/lib/postgresql/data ]

  asset-db:
    image: postgres:16
    environment:
      POSTGRES_DB: assetdb
      POSTGRES_USER: asset
      POSTGRES_PASSWORD: asset
    ports:
      - "5432:5432"
    volumes: [ asset_data:/var/lib/postgresql/data ]

  portfolio-db:
    image: postgres:16
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    ports:
      - "5434:5432"
    volumes: [ portfolio_data:/var/lib/postgresql/data ]

  notifications-db:
    image: postgres:16
    environment:
      POSTGRES_DB: notificationsdb
      POSTGRES_USER: notifications
      POSTGRES_PASSWORD: notifications
    volumes: [ notifications_data:/var/lib/postgresql/data ]

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  kafka:
    image: dhi.io/kafka:4.3-native
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS_COMMAND_NAME: 'CONTROLLER'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    ports:
      - "9092:9092"

volumes:
  keycloak_data:
  market_data:
  asset_data:
  notifications_data:
  portfolio_data: