server:
  port: 8082
spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://portfolio-db:5432/portfoliodb
    username: portfolio
    password: portfolio
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/trading-platform
          jwk-set-uri: http://keycloak:8080/realms/trading-platform/protocol/openid-connect/certs

market-service:
  base-url: http://market-service:8081

logging:
  level:
    tn.utm.nainternship.portfolioservice: DEBUG
